umapp/urls.py
from django.urls import path
from .views import *
# from .views import HomeView, ContactView

app_name="umapp"
urlpatterns=[
    path('', HomeView.as_view(), name='home'),
    path('signup/', SignupView.as_view(),name="signup"),
    path('signin/', SigninView.as_view(),name="signin"),
    path('signout/', SignoutView.as_view(),name="signout"),
    path('um-admin',AdminHomeView.as_view(),name="admin"),
    path('um-admin/blog/create',AdminBlogCreateView.as_view(),name="adminblogcreate"),
    path('blog/list/', BlogListView.as_view(), name="bloglist"),
    path('blog/<int:pk>/detail/', BlogDetailView.as_view(), name="blogdetail"),
    path('blog/<int:pk>/comment/', BlogCommentView.as_view(), name="blogcomment"),
    path('passwordchange/',PasswordChangeView.as_view(),name='passwordchange'),
    path('search/',SearchView.as_view(),name='search'),
    path('commentlist/',CommentListView.as_view(),name='comment'),
]

umproject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('umapp.urls')),

]

umapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Blog(models.Model):
	title=models.CharField(max_length=300)
	image=models.ImageField(upload_to="blogs")
	context=models.TextField()
	created_at=models.DateTimeField(auto_now_add=True)
	author=models.ForeignKey(User,on_delete=models.CASCADE)

	def __str__(self):
		return self.title

class Comment(models.Model):
	commenter=models.ForeignKey(User, on_delete=models.CASCADE)
	blog=models.ForeignKey(Blog, on_delete=models.CASCADE)
	date=models.DateTimeField(auto_now_add=True)
	comment=models.TextField()

	def __str__(self):
		return self.blog.title

umapp/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import *

class SignupForm(forms.Form):
	username=forms.CharField(widget=forms.TextInput())
	email=forms.CharField(widget=forms.EmailInput())
	password=forms.CharField(widget=forms.PasswordInput())
	confirm_password=forms.CharField(widget=forms.PasswordInput())

	def clean_username(self):
		uname=self.cleaned_data["username"]
		if User.objects.filter(username=uname).exists():
			raise forms.ValidationError("User with this username already exists")


		return uname

	def clean_confirm_password(self):
		password=self.cleaned_data["password"]
		c_password=self.cleaned_data["confirm_password"]
		if password != c_password:
		 	raise forms.ValidationError("password didn't match")

		return c_password

class SigninForm(forms.Form):
	username=forms.CharField(widget=forms.TextInput())
	password=forms.CharField(widget=forms.PasswordInput())

class BlogForm(forms.ModelForm):
	class Meta:
		model=Blog
		fields=["title","image","context"]

class CommentForm(forms.ModelForm):
	class Meta:
		model=Comment
		fields=["comment"]

class PasswordChangeForm(forms.Form):
	old_password= forms.CharField(widget=forms.PasswordInput())
	new_password= forms.CharField(widget=forms.PasswordInput())
	confirm_new_password= forms.CharField(widget=forms.PasswordInput())

	def clean_confirm_new_password(self):
		a=self.cleaned_data["new_password"]
		b=self.cleaned_data["confirm_new_password"]
		if a != b:
			raise forms.ValidationError("password didn't match")

		return b

umapp/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from .forms import *
from django.shortcuts import render,redirect
from django.views.generic import *
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
class HomeView(TemplateView):
	template_name='home.html'

class SignupView(FormView):
	template_name= "signup.html"
	form_class= SignupForm
	success_url="/"

	def form_valid(self, form):
		uname=form.cleaned_data['username']
		email=form.cleaned_data['email']
		password=form.cleaned_data['password']
		print(uname,email,password)
		User.objects.create_user(uname,email,password)

		return super().form_valid(form)



class SigninView(FormView):
	template_name='signin.html'
	form_class=SigninForm
	success_url="/"


	def form_valid(self,form):
		uname=form.cleaned_data["username"]
		pword=form.cleaned_data["password"]
		print(uname,pword)
		user=authenticate(username=uname,password=pword)
		if user is not None:
			login(self.request,user)
		else:
			return render(self.request,"signin.html",
				{"error":"invalid username or password","form":form})

		return super().form_valid(form)

class SignoutView(View):
	def get(self,request):
		logout(request)
		return redirect("/signin/")
'''
class AdminHomeView(LoginRequiredMixin,TemplateView):
	template_name="adminhome.html"
	login_url="/signin/"
'''


class AdminHomeView(TemplateView):
	template_name="adminhome.html"
	def dispatch(self,request,*args,**kwargs):
		if request.user.is_authenticated:
			pass
		else:
			return redirect("/signin/")

		return super().dispatch(request,*args,**kwargs)


class AdminBlogCreateView(LoginRequiredMixin,CreateView):
	template_name="adminblogcreate.html"
	form_class=BlogForm
	success_url="/um-admin"
	def form_valid(self,form):
		logged_in_user=self.request.user
		form.instance.author=logged_in_user


		return super().form_valid(form)


class BlogListView(ListView):
	template_name = 'bloglist.html'
	queryset = Blog.objects.all()
	context_object_name = "allblogs"


class BlogDetailView(DetailView):
	template_name = "blogdetail.html"
	model = Blog
	context_object_name = "blogobject"

	def get_context_data(self,**kwargs):
		context=super().get_context_data(**kwargs)
		context["form"]=CommentForm
		return context


class BlogCommentView(CreateView):
	template_name="blogcomment.html"
	form_class=CommentForm
	success_url="/blog/list/"

	def dispatch(self,request,*args,**kwargs):
		if not request.user.is_authenticated:
			return redirect("/signin/")
		return super().dispatch(request,*args,**kwargs)



	def form_valid(self,form):
		form.instance.commenter=self.request.user
		blog_id=self.kwargs["pk"]
		blog=Blog.objects.get(id=blog_id)
		form.instance.blog=blog


		return super().form_valid(form)

	def get_success_url(self):
		blog_id=self.kwargs["pk"]
		url_to_redirect="/blog/"+str(blog_id)+ "/detail/"

		return url_to_redirect


class PasswordChangeView(FormView):
	template_name='passwordchange.html'
	form_class=PasswordChangeForm
	success_url=reverse_lazy('umapp:home')

	def form_valid(self, form):
		a = form.cleaned_data['old_password']
		b = form.cleaned_data['new_password']
		logged_in_user = self.request.user
		user = authenticate(username=logged_in_user.username, password=a)
		if user is not None:
			logged_in_user.set_password(b)
			logged_in_user.save()
		else:
			return render(self.request, "passwordchange.html", {
				'error': "Your old password is incorrect", 
				'form': form
				})

		return super().form_valid(form)


class SearchView(TemplateView):
	template_name= "search.html"

	def get_context_data(self,**kwargs):
		context= super().get_context_data(**kwargs)
		keyword= self.request.GET["barshat"]
		#keyword= self.request.GET.get("barshat")
		a= Blog.objects.filter(Q(title__icontains = keyword) | Q(context__icontains= keyword))
		page = self.request.GET.get('page', 1)

		paginator = Paginator(a, 3)
		try:
			results = paginator.page(page)
		except PageNotAnInteger:
			results = paginator.page(1)
		except EmptyPage:
			results = paginator.page(paginator.num_pages)

		context["results"]= results



		return context


class CommentListView(ListView):
	template_name= "commentlist.html"
	model= Comment
	context_object_name= "comments"
	paginate_by= 2


	

templates/adminblogcreate.html
{% extends "base.html" %}

{% block content %}

<h4> Blog Form</h4>
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<button>submit</button>
</form>


{% endblock %}

templates/adminhome.html
{% extends "base.html" %}
{% block content %}
<h3> This is protected page</h3>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
	{% if request.user.is_authenticated %}
	<p>logged in as: <span class="text-info">{{request.user}}</span></p>
	<a href="/signout/">Signout</a>
	{% else %}
	<a href="/signin/"> Sign in
	</a>
	<a href="/signup/"> signup</a>
	{% endif %}
	<a href="{% url 'umapp:bloglist' %}">All Blogs</a>
	<hr>

	<form method= "GET" action= "/search/">
		<input type= "text" name= "barshat" placeholder="search here" value= "{{request.GET.barshat}}">
		<button> Search</button>
	</form> 
	{% block content %}
	
	
	
	{% endblock %} 

</body>
</html>

templates/blogcomment.html
{% extends "base.html" %}

{% block content %}

<h4> Comment Form</h4>
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<button>submit</button>
</form>


{% endblock %}
 

templates/blogdetail.html
{% extends 'base.html' %}

{% block content %}
<h3>{{blogobject.title}}</h3>
<img src="{{blogobject.image.url}}" width="500">
<p>{{blogobject.context}}</p>
<p>Author: {{blogobject.author}}</p>
<p>Posted on: {{blogobject.created_at}}</p>
<h5>All comments</h5>
{% for comment in blogobject.comment_set.all%}
<li>{{comment.commenter}} says:{{comment.comment}} {{comment.date|timesince}} ago</li>
{% endfor %}
<h4>Comment Here</h4>
<form method="POST" action="{% url 'umapp:blogcomment' blogobject.pk %}">
	{% csrf_token %}
	{{form.as_p}}
	<button>Comment</button>


</form>
{% endblock %}

templates/bloglist.html
{% extends 'base.html' %}

{% block content %}
<h3>All Blogs</h3>
{% for blog in allblogs %}
<li><a href="{% url 'umapp:blogdetail' blog.id %}">{{blog.title}}</a></li>
{% endfor %}
{% endblock %}

templates/commentlist.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
{% for comment in comments %}
{{comment.commenter}}<br>
{{comment.comment}}<hr>

{% endfor %}

{% if page_obj.has_other_pages %}
<ul class="pagination">
	{% if page_obj.has_previous %}
	<li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
	{% else %}
	<li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
	{% endif %}
	{% for n in page_obj.paginator.page_range %}
		{% if page_obj.number == n %}
			<li class="page-item active"><span class="page-link">{{ n }} <span class="sr-only">(current)</span></span></li>
		{% else %}
			<li class="page-item"><a class="page-link" href="?page={{ n }}">{{n}}</a></li>
		{% endif %}
	{% endfor %}
	{% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number}}">Next</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">Next</span></li>
    {% endif %}
</ul>
{% endif %}



{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
	<h1> This is home page </h1>

{% endblock %}

templates/javascript/index.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h2 id="myhs">Hello World</h2>
	<p id="myp"></p>

	<input type="text" name="Roll_no" id="my_input">
	<button onclick="test()">Submit</button>







<script type="text/javascript">
	alert("Hello World");
	console.log("Hello World");

	var a=document.getElementById("myhs")
	a.innerHTML= "my name is barshat";

	var b=document.getElementById("myp")
	b.innerHTML= "I live in Nepal";

	a.style.color="red";

	test =function(){
		var a=document.getElementById("my_input");
		alert(a.value);

		}






</script>





</body>
</html>

templates/javascript/passwordvalidation.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

	<h3> Password Form </h3>
	<form>
			<p id= "p1_error"></p>
		<p >
			<input type="password" name="p1" id="p1">

		</p>	
		<p><input type="password" name="p2" id="p2">
			<p id="p2_error"></p>
		</p>
		<button type= "button" id="submit"> Submit </button>
	</form>



	<script src= "https://code.jquery.com/jquery-3.4.1.min.js">
  	
  
  </script>
  <script type="text/javascript">
  	$(document).ready(function(){

  		
  		$("#submit").on("click",function(){

  			var p1_val= $("#p1").val();
  			var p2_val= $("#p2").val();
  			if (p1_val == ""){
  				$("#p1_error").text("please enter password");

  			}
  			if (p2_val == ""){
  				$("#p2_error").text("please enter password");
  			}


  			if(p1_val != p2_val){ 
  				$("#p2_error").text("password didnt match").css("color","red");
  			}
  			
  			else{
  				$("#p2_error").text("password match").css("color","green");
  			}

  		})
  	})
  </script>
  			


</body>
</html>

templates/javascript/passwordvalidation2.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

	<h3> Password Form </h3>
	<form>
			<p id= "p1_error"></p>
		<p >
			<input type="password" name="p1" id="p1">

		</p>	
		<p><input type="password" name="p2" id="p2">
			<p id="p2_error"></p>
		</p>
		<button type= "button" id="submit"> Submit </button>
	</form>



	<script src= "https://code.jquery.com/jquery-3.4.1.min.js">
  	
  
  </script>
  <script type="text/javascript">
  	$(document).ready(function(){
  		$("#p1, #p2").on("keyup",function(){
  			var p1_val= $('#p1').val();
  			var p2_val= $('#p2').val();
  			if (p1_val != p2_val){
  				$("#p2_error").text("password didnt match").css("color","red");
  			}
  			else{
  				$("#p2_error").text("password Matched").css("color","green");
  			}

  		
  		})


  	})
  </script>
  			


</body>
</html>

templates/passwordchange.html
{% extends "base.html" %}

{% block content %}

<h4> Password Change Form</h4>
{% if error %}
<li class="text-danger"> {{error}} </li>
{% endif %}
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<button>Change</button>
</form>


{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>Search Results</h3><hr>
{% for data in results %}
<li><a href= "{% url 'umapp:blogdetail' data.id %}">{{data.title}}</a></li>
<img src="{{data.image.url}}" width= "200">
{% empty %}
<li>No results found</li>

{% endfor %}



{% if search_results.has_other_pages %}
<ul class="pagination">
	{% if search_results.has_previous %}
	<li class="page-item"><a class="page-link" href="?page={{ search_results.previous_page_number }}&keyword={{request.GET.keyword}}">Previous</a></li>
	{% else %}
	<li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
	{% endif %}
	{% for n in search_results.paginator.page_range %}
		{% if search_results.number == n %}
			<li class="page-item active"><span class="page-link">{{ n }} <span class="sr-only">(current)</span></span></li>
		{% else %}
			<li class="page-item"><a class="page-link" href="?page={{ n }}&keyword={{request.GET.keyword}}">{{n}}</a></li>
		{% endif %}
	{% endfor %}
	{% if search_results.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ search_results.next_page_number}}&keyword={{request.GET.keyword}}">Next</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">Next</span></li>
    {% endif %}
</ul>
{% endif %}

{% endblock %}

templates/signin.html
{% extends "base.html" %}

{% block content %}

<h4> Signin Form</h4>
{% if error %}
<li class="text-danger"> {{error}} </li>
{% endif %}
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<button>Signin</button>
</form>


{% endblock %}

templates/signup.html
{% extends "base.html" %}

{% block content %}

<h4> Signup Form</h4>
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<button>Signup</button>
</form>


{% endblock %}